apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: 'jnlp'
  name: 'jnlp'
  namespace: 'jnlp'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 'jnlp'
  template:
    metadata:
      labels:
        app: 'jnlp'
    spec:
      containers:
        -
          image: 'yuxel/jnlp:latest'
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          imagePullPolicy: Always
          name: 'jnlp'
          ports:
            - containerPort: 22
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  name: 'jnlp'
  namespace: 'jnlp'
  labels:
    app: 'jnlp'
spec:
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
  selector:
    app: 'jnlp'
  type: ClusterIP
